input {
	file {
		path => "/etc/logstash/data/app_access.csv"
		start_position => "beginning"
		sincedb_path => "/dev/null"
	}
}

filter {
	csv {
		columns => [datetime,username,srcip,company,result,customerid]
	}
}

output {
	elasticsearch { hosts => ["localhost:9200"] }
}
