input {
    file {
        path => "/etc/logstash/data/app_access.csv"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}

filter {
    csv {
        columns => ["datetime", "username", "srcip", "company", "result", "customerid"]
    }
    
    date {
        match => ["datetime", "UNIX_MS"]
        target => "datetime"
    }
    geoip  {
	source => "srcip"
	target => "geoip_src"
    }
    if [result] == "PASS" {
	mutate {
		replace => ["result" , "success"]
	}
    }
    mutate {
        remove_field => ["message"]
    }
}

output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "app-access"
    }
}
