input {
	file {
		path => "/etc/logstash/data/app_access.csv"
		start_position => "beginning"
		sincedb_path => "/dev/null"
	}
}

filter {
	
}

output {
	elasticsearch { hosts => ["localhost:9200"] }
}
